### ISSUE TITLE
AssertionError on extracting a file from a 7z archive

### ISSUE THREAD

**Issue by brijmohan** [fancycode/pylzma#17]
Can anyone help solving this issue?
I am using the current master version from git.
```
Traceback (most recent call last):
  File "/home/brij/Documents/moody/moody_ws/MoodyUtils/com/moody/qareaders/SOXmlParser.py", line 38, in <module>
    FileUtil.extractPostsXml(cfile, OUTPUT_XML)
  File "/home/brij/Documents/moody/moody_ws/MoodyUtils/com/moody/utils/FileUtil.py", line 66, in extractPostsXml
    o.write(arch.getmember("Posts.xml").read())
  File "/usr/local/lib/python2.7/dist-packages/pylzma-0.4.4_37_gbb2bdev-py2.7-linux-x86_64.egg/py7zlib.py", line 575, in read
    data = getattr(self, decoder)(coder, data)
  File "/usr/local/lib/python2.7/dist-packages/pylzma-0.4.4_37_gbb2bdev-py2.7-linux-x86_64.egg/py7zlib.py", line 646, in _read_bzip
    return self._read_from_decompressor(coder, dec, input)
  File "/usr/local/lib/python2.7/dist-packages/pylzma-0.4.4_37_gbb2bdev-py2.7-linux-x86_64.egg/py7zlib.py", line 611, in _read_from_decompressor
    assert len(tmp) > 0
AssertionError
```

**Comment by fancycode** [comment]
Sorry for the noise, took a while to get this tested by Travis.
